### ISSUE TITLE
Correct product-page display when both onetime charge and price-by-attributes apply

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#156]
... otherwise, the top/bottom price blocks look like
![image](https://user-images.githubusercontent.com/2685585/203310586-be4b975a-6f42-4d3c-99d9-0f8970dfdb29.png)

**Comment by lat9** [comment]
Crud, I didn't see that the setting of `$one_time` was only created when a product has attributes.  Now seeing logs like
```
[24-Nov-2022 14:04:18 America/New_York] Request URI: /zc158/index.php?main_page=product_info&cPath=22&products_id=105, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc158\includes\templates\bootstrap\templates\tpl_product_info_display.php(242): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\pages\product_info\main_template_vars.php(156): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\zc158\includes\templates\bootstrap\common\tpl_main_page.php(202): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\index.php(94): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined variable $one_time in C:\xampp\htdocs\zc158\includes\templates\bootstrap\templates\tpl_product_info_display.php on line 242.
```

**Comment by lat9** [comment]
For whatever reason (!) the layout of the `product_info` display is different from all the other `product_xx_info` display templates.  In the interest of time, I'm just going to fix that template layout and will add to the future to-do list to review/refactor all these templates.
