### ISSUE TITLE
Correct PHP warning when product has quantity discounts

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#161]
Seeing logs of the ilk:
```
[25-Nov-2022 13:33:55 America/New_York] Request URI: /zc158/index.php?main_page=product_info&cPath=54_56&products_id=159, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc158\includes\templates\bootstrap\modalboxes\tpl_attributes_qty_prices.php(101): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\templates\bootstrap\templates\tpl_modules_attributes.php(77): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\zc158\includes\templates\bootstrap\templates\tpl_product_info_display.php(205): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\includes\modules\pages\product_info\main_template_vars.php(156): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\zc158\includes\templates\bootstrap\common\tpl_main_page.php(202): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\zc158\index.php(94): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined array key "products_tax_class_id" in C:\xampp\htdocs\zc158\includes\templates\bootstrap\modalboxes\tpl_attributes_qty_prices.php on line 101.
```

**Comment by lat9** [comment]
There's the correction; re-factoring coming up.
